version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest  # Use the official MongoDB image
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SijJXd7itY1yruVEmaSdvO06
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongodb-data:/data/db  # Persist MongoDB data between container restarts
    ports:
      - "27017:27017"  # Expose MongoDB port

  # Node.js application service
  node-app:
    build: .  # Build the Dockerfile in the current directory
    container_name: node-app
    restart: always
    environment:
      DB_URI: mongodb://root:SijJXd7itY1yruVEmaSdvO06@172.21.43.202:27017/admin?retryWrites=true&w=majority
      JWT_SECRET: "4d9c8c881fcb09e4ab22b448f8b2af78b16740fa9e2df3358dae6e46351b14d1"
    depends_on:
      - mongodb
    ports:
      - "5000:5000"  # Expose the port the app listens on
    volumes:
      - .:/usr/src/app  # Mount the application directory to allow live code changes
      - /usr/src/app/node_modules
    networks:
      - app-network

volumes:
  mongodb-data:  # Declare a named volume for MongoDB data persistence

networks:
  app-network:
    driver: bridge
